name: Clone from Gitlab



on:
  workflow_dispatch:
    inputs:
      branch:
        default: master
jobs:
  clone:
    name: Clone repo
    runs-on: ubuntu-latest
    steps:
      - name: "Clone from Gitlab"
        run: | 
          git clone https://gitlab.c3sl.ufpr.br/mmcavazotti/the-algorithm-box.git
      - name: "Checkout branch"
        run: | 
          cd the-algorithm-box
          git checkout ${{ inputs.branch}}
      - name: "Push to Github"
        run: | 
          cd the-algorithm-box
          git remote add github https://${{secrets.GITHUB_TOKEN}}@github.com/mcavazotti/the-algorithm-box.git
          git push github
